### ISSUE TITLE
Tab and Shit+Tab change the menu but then the menu closes right after

### ISSUE THREAD

**Issue by av1155** [patrickpichler/hovercraft.nvim#6] opened 2024-09-13 22:29 UTC
Im not sure what i'm doing wrong, but the menu closes if i press tab or shift+tab. It used to work (cycle through the different options) when I first set this plugin up.

**nvim/plugins/astrolsp.lua:**
```
return {
                ["<leader>ld"] = {
                    function()
                        local hovercraft = require "hovercraft"
                        if hovercraft.is_visible() then
                            hovercraft.enter_popup()
                        else
                            hovercraft.hover()
                        end
                    end,
                    desc = "Hover LSP provider",
                },
 }
```
           
           
                
   **nvim/plugins/user.lua:**
```
   return {
   {
        "patrickpichler/hovercraft.nvim",

        dependencies = {
            { "nvim-lua/plenary.nvim" },
        },

        opts = function()
            return {
                window = {
                    border = "rounded",
                },

                -- keys = {
                --     { "<C-u>", function() require("hovercraft").scroll { delta = -4 } end },
                --     { "<C-d>", function() require("hovercraft").scroll { delta = 4 } end },
                --     { "<TAB>", function() require("hovercraft").hover_next() end },
                --     { "<S-TAB>", function() require("hovercraft").hover_next { step = -1 } end },
                -- },
            }
        end,
    },
 }
```

**Comment by patrickpichler** [comment] 2024-09-14 06:33
Hey, 
Thanks for the bug report. The issue is a regression introduced with the latest bugfix, where keymaps didn't get cleared. I will have a look!

**Comment by patrickpichler** [comment] 2024-09-14 06:48
The issue should be fixed 😄 
Let me know if you encounter any more problems :)

**Closed** 2024-09-14 06:47 UTC

**Comment by av1155** [comment] 2024-09-15 19:49
Fixed! Thank you :)
